### ISSUE TITLE
[BUG] Remove `_app.asar` copy caveat

### ISSUE THREAD

**Issue by MeguminSama** [MeguminSama/Discord-ModHook#1]
tl;dr

ModHook works by proxying fs calls to `%localappdata%/discord/app-...../resources/app.asar` to `./resources/vencord.asar/`
and *should* proxy `%localappdata%/discord/app-..../resources/_app.asar` to `%localappdata%/discord/app-...../resources/app.asar`

but i'm having a lot of trouble differentiating between the two calls (to know whether i'm supposed to return the `./resources` version or the `%localappdata%` version)

Relevant code:
https://github.com/MeguminSama/Discord-ModHook/blob/aca8df9e010b038f67d11ba962e19ab01344b1ab/ModHook/Injection.cpp#L14-L76

**Comment by MeguminSama** [comment]
Fixed in https://github.com/MeguminSama/Discord-ModHook/commit/1ded85b083f0a404806ae4962933999cf280691e :D

**Comment by kotx** [comment]
:D

**Comment by MeguminSama** [comment]
:D
